### ISSUE TITLE
[UI/UX] Repository - RQL section visual enhancements

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#89] opened 2016-06-14 10:44 UTC
I think we could improve a bit the RQL section visually

- the property descriptor list is a bit small in height, for items with a lot of properties you need to scroll a lot
 - maybe place this elsewhere? that would solve the issue with sharing this space with saved queries.
 - or make it longer or have an "extended" mode.

- the "set property" button should have its own column for better alignment, and could use the "bda-button" style

**Comment by sixdouglas** [comment] 2016-06-14 10:50
Using tabs may be a good solution to share the space.
One for Shared Queries, the other one for the Properties

**Comment by jc7447** [comment] 2016-06-14 11:04
Yep, Tab is a good idea. If we have a default item descriptor we can display the properties tab by default, otherwise we display the saved queries tab.

Agree to improve the "set property" button.

Not sure if display an higher list will change a lot, if the list is too big, we will have to scroll the page instead of the list. We can probably increase a bit the height and the width so we will have less cell with 2 lines.

Also we can add a checkbox to activate/deactivate the replacement of white-space with a special character

**Comment by troussej** [comment] 2016-06-15 07:40
Agreed that increasing a lot the size of the box won't solve the issue.
That's why I suggest an expand mode instead, if you want quick access to all the properties.
Maybe we should actually merge this with the propertyDescriptors section in some way

**Comment by troussej** [comment] 2016-06-17 13:15
- in the same idea, maybe rethink the placement of the "add, add & enter, clear, enter" buttons, to put all of them in a same location.
- when displaying the items as an table, maybe align the different lines, it's a bit wonky now

**Comment by jc7447** [comment] 2016-06-20 12:09
> in the same idea, maybe rethink the placement of the "add, add & enter, clear, enter" buttons, to put all of them in a same location.

I'm afraid we will lose people used to the enter button.  Also but all buttons together can be confusing as well. For what I can see, people seems to understand this part quite good.

One solution to get ride of most of the buttons can be to remove the toolbar and propose auto-completion, but it's a huge change and I'm not sure it's for the best.

> when displaying the items as an table, maybe align the different lines, it's a bit wonky now

Not sure to understand, do you have a scenario to reproduce or an example ?

**Comment by troussej** [comment] 2016-06-20 14:29
> I'm afraid we will lose people used to the enter button. Also but all buttons together can be confusing as well. For what I can see, people seems to understand this part quite good.

Yeah, maybe it's just me, I'd like the "clear" button near the "add" one, it's usefull when doing a lot of queries. Maybe my issues will be solved when we have the super-mega-bda-script-awesome ;)

for the second point I will get a screenshot when I can.

**Comment by jc7447** [comment] 2016-09-18 12:11
Since tabs have been implemented, I'm closing this task .
We can continue to discuss about visual enhancement trough new issue

**Closed by jc7447** 2016-09-18 12:11 UTC
Labels: enhancement
